version: "3.8"

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nextjs-app:
    build:
      context: ./frontapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
