server:
  port: 8090
spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./medium;MODE=MYSQL;AUTO_SERVER=TRUE
  h2:
    console:
      settings:
        web-allow-others: true
