server:
  port: 8080
spring:
  datasource:
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medium_prod?useSSL=false&serverTimezone=UTC
